[package]
name = "cfn-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version = "0.8.1", features = ["macros"]}
bon = "3.3.2"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"
tokio = "1.43.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
